require("dotenv").config();
const { sendSlackMessage, joinSlackChannel } = require("./utils/slack.util");

console.log("🚀 Slack Notifier 🚀");
// joinSlackChannel(process.env.SLACK_CHANNEL_ID);
const sendMessage = async (message) => {
  await sendSlackMessage(message);
};

sendMessage("This is generated by Notifier Test App");
